### ISSUE TITLE
Questions about the model provided.

### ISSUE THREAD

**Issue by XueyangWWW** [yu02019/BEN#1]
Hi @yu02019, 

May I ask which model is better for me to process the T1w modality of macaque?
I downloaded the model you provided on Google Drive, but there is only macaque T2w and EPI to choose from.

**Comment by yu02019** [comment]
Hi  XueyangWWW,


Sorry for the late response. I have double checked the source files, I find that the naming error was caused by a manual modification of the folder before the pretrained weights were uploaded to Drive. 'Macaque-T2WI-76-%30-DA_08250149' should actually be 'Macaque-T1WI-76-%30-DA_08250149'.

Additionally, we updated the parameter input interface for BEN, and we retrained it on the multi-center data for Macaque-T1 to  better fit new pipeline. You can find it on Google Drive (Macaque-T1WI-76_03222044).

Concretely, we use the following commands to update BEN:
`
python BEN_DA.py
-t
E:\New\Macaque\dataset\src
-l
E:\New\Macaque\dataset\label
-r
E:\New\Macaque\dataset\src
-prefix
Macaque-T1WI-76
-check
RPI
`
`
python BEN_infer.py
-i
E:\New\Macaque\dataset\src-reserve
-o
E:\New\Macaque\dataset\pred
-weight
weight/Macaque-T1WI-76_03222044/.hdf5
`

the reference logs file:
[logs.zip](https://github.com/yu02019/BEN/files/11048394/logs.zip)

If you have any further questions, feel free to pose it here.
